# fly.toml app configuration file generated for zaban on 2026-02-08T18:30:08-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zaban'
primary_region = 'iad'

[build]

[env]
  DB_PATH = '/data/zaban.db'
  NODE_ENV = 'production'

[[mounts]]
  source = 'zaban_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
